#!/bin/sh
####################################################################
## makeVAP
##
## This script is used to create AP or Station instances (VAPs).  It
## will NOT actually join the bridge or do any RF configuration.
##
## The form of the command is
##
## makeVAP <Mode> <ESSID> <Channel_String> <beaconint>
##
## Where
##     Mode:    Either ap, ap-wds, sta, or sta-wds
##              (access point or station)
##     ESSID:   ESSID String
##     Channel: String indicating the channel configuration.  This is in
##     String   the form inst:RF:channel:mode where
##              Inst = Interface instance (which radio, 0 or 1)
##              RF   = RF indicates radio should be configured with the specified parameters
##              channel = channel to put the AP on, use 11A or 11G to scan
##              mode = operating mode, one of
##              11AST         : 11 A Static Turbo (Legacy)
##              AUTO          : Legacy Scan Mode
##              11A           : Legacy 11A mode
##              11B
##              11G
##              FH
##              TA
##              TG
##              11NAHT20
##              11NGHT20
##              11NAHT40PLUS
##              11NAHT40MINUS
##              11NGHT40PLUS
##              11NGHT40MINUS
##              11NAHT40 (valid only when channel=11na)
##              11NGHT40 (valid only when channel=11ng)
##
##
## beaconint:   This is the beacon interval desired for this VAP.  Note
##              that this is system wide, and will override the current
##              beacon interval for ALL vaps.  You MUST also include the
##              RF command for this option.
##
## Examples:
##   Access Point with RF
##      makeVAP ap OpenAP 0:RF:6:
##   Access Point with RF, beacon interval of 400 ms
##      makeVAP ap OpenAP RF 400
##   Access Point w/o RF
##      makeVAP ap NormAP
##   WDS Root AP
##      makeVAP ap-wds RootAP RF
##   WDS Repeater (two commands)
##      makeVAP sta-wds RPTR RF
##      makeVAP ap-wds RPTR
##
###################################################################

echo "$0 $1 $2 $3 $4 $5 $6"

#+++ Alphanetworks: hendry.
. /etc/ath/apcfg_alpha
#--- Alphanetworks: hendry.


MODE=`echo $1 | cut -f 1 -d '-'`
SUB_MODE=`echo $1 | cut -f 2 -d '-'`
IND_MODE=`echo $1 | cut -f 3 -d '-'`

ESSID=$2


#+++ Alphanetworks: hendry
PARAMS=$3
BANDMODE=`echo $PARAMS 		| scut -p "BANDMODE=" 		| cut -f 1 -d ';'`
CH_MODE=`echo $PARAMS 		| scut -p "CH_MODE=" 		| cut -f 1 -d ';'`
PRI_CH=`echo $PARAMS 		| scut -p "PRI_CH=" 		| cut -f 1 -d ';'`
PUREN=`echo $PARAMS 		| scut -p "PUREN=" 			| cut -f 1 -d ';'`
PUREG=`echo $PARAMS 		| scut -p "PUREG=" 			| cut -f 1 -d ';'`
AP_CHANBW=`echo $PARAMS 	| scut -p "AP_CHANBW=" 		| cut -f 1 -d ';'`
AP_HIDESSID=`echo $PARAMS 	| scut -p "AP_HIDESSID=" 	| cut -f 1 -d ';'`
AP_WMM=`echo $PARAMS 		| scut -p "AP_WMM=" 		| cut -f 1 -d ';'`
RF=`echo $PARAMS 			| scut -p "RF=" 			| cut -f 1 -d ';'`
R_SHORTGI=`echo $PARAMS 	| scut -p "R_SHORTGI=" 		| cut -f 1 -d ';'`
BEACONINT=`echo $PARAMS 	| scut -p "BEACONINT=" 		| cut -f 1 -d ';'`
ATH_NAME=`echo $PARAMS  	| scut -p "ATH_NAME="       | cut -f 1 -d ';'`

#settings from  atheros poor documentation !!
AP_STARTMODE=dual
TX_CHAINMASK=7
RX_CHAINMASK=7
TX_CHAINMASK_2=7
RX_CHAINMASK_2=7
# 11AC parameters
AMSDU=2
AMPDU=64
NSS=3
VHTMCS=7
LDPC=1

if [ "${BANDMODE}" = "5G" ]; then
	IFNUM=0
else
	IFNUM=1
fi

echo bandmode =$BANDMODE 	> /dev/console
echo ssid     =$SSID 		> /dev/console
echo wlanmode =$CH_MODE 	> /dev/console
echo chan_bw  =$AP_CHANBW 	> /dev/console
echo channel  =$PRI_CH 		> /dev/console
echo hidessid =$AP_HIDESSID > /dev/console
echo wmm      =$AP_WMM 		> /dev/console
echo puren    =$PUREN 		> /dev/console
echo pureg    =$PUREG 		> /dev/console
echo rf		  =$RF	 		> /dev/console
echo ATH_NAME =$ATH_NAME 	> /dev/console
#--- Alphanetworks



if [ "${1}" = "" ]; then
    echo "makeVAP usage"
    echo "makeVAP mode essid IFstr"
    echo
    echo "mode: [ap | ap-wds | sta | sta-wds | sta-fwd]"
    echo "essid: up to 32 character ESSID string"
    echo "RF: Include RF commands"
    echo "beaconint: Beacon interval, milliseconds"
    echo
    exit
fi


##
## Need to select the proper radio parameters based on the interface
## ID
##

if [ "${IFNUM}" = "1" ]; then
    #R_SHORTGI=$SHORTGI_2
	R_CWMMODE=$CWMMODE_2
    R_AMPDUENABLE=$AMPDUENABLE_2
	R_AMPDUFRAMES=$AMPDUFRAMES_2
	R_AMPDULIMIT=$AMPDULIMIT_2
	R_TXCHAIN=$TX_CHAINMASK_2
	R_RXCHAIN=$RX_CHAINMASK_2
else
    #R_SHORTGI=$SHORTGI
	R_CWMMODE=$CWMMODE
    R_AMPDUENABLE=$AMPDUENABLE
	R_AMPDUFRAMES=$AMPDUFRAMES
	R_AMPDULIMIT=$AMPDULIMIT
	R_TXCHAIN=$TX_CHAINMASK
	R_RXCHAIN=$RX_CHAINMASK
fi



##
## First, let's see if we have the modules loaded.  If not, call the
## rc.wlan script to load them
##

# +++ Alphnetworks: hendry, we close this. Only insert modules at init
#MODLIST=`lsmod | grep ath_hal`
#
#if [ "${MODLIST}" = "" ]; then
#    /etc/rc.d/rc.wlan up
#
#    ##
#	## Check for bad return value.  If so, exit
#	##
#
#	if [ $? != 0 ]; then
#	    exit 255
#	fi
#else
#    echo "Modules already loaded"
#fi
# --- Alphnetworks: hendry

echo Creating ${MODE} for "${ESSID}" on ${BRIDGE}

##
## Create the instance
##

if [ "${MODE}" = "sta" ]; then
    if [ "${IND_MODE}" = "ind" ]; then
       	APNAME=`wlanconfig ath create wlandev wifi$IFNUM wlanmode ${MODE}`
    else
        APNAME=`wlanconfig ath create wlandev wifi$IFNUM wlanmode ${MODE} nosbeacon`
    fi
    APMODE="mode managed"
else
    APNAME=`wlanconfig ${ATH_NAME} create wlandev wifi$IFNUM wlanmode ${MODE}`
    if [ "${MODE}" = "adhoc" ]; then
        APMODE="mode adhoc"
    else
        APMODE="mode master"
    fi
fi

echo Added ${APNAME} ${APMODE}

##
## Enable WDS if selected
##

if [ "${SUB_MODE}" = "wds" ]; then
    iwpriv ${APNAME} wds 1
    echo "Enable wds on ${APNAME}"    
fi

## AP_STARTMODE = extap
## This will come for the station vap of repeater
if [ "${SUB_MODE}" = "ext" ]; then
	iwpriv ${APNAME} extap 1
	echo "Enable extap on ${APNAME}"	
fi


##
## Enable VAP Independant mode - for repeater-ind conf
##

if [ "${IND_MODE}" = "ind" ]; then
    if [ $PRI_CH = 11na -o $PRI_CH = 11ng ]; then
        echo "Auto Channel selection is not allowed for VAP independant mode"
        exit 255
    else
        iwpriv ${APNAME} vap_ind 1
    fi
fi

## ACS is only for AP only or Ad-Hoc mode
if [ "${MODE}" = "sta" ]; then
    if [ $CH_MODE = 11NAHT40 -o $CH_MODE = 11NGHT40 ]; then
        echo "Auto Channel selection is not for sta mode"
        exit 255
    fi
fi

##
## Enable Station forwarding if selected
##

if [ "${SUB_MODE}" = "fwd" ]; then
    iwpriv ${APNAME} stafwd 1
    echo "Enable stafwd on ${APNAME}"    
fi

##
## Disable Background Scan
##

#+++Alphanetworks: hendry
#iwpriv ${APNAME} bgscan 0
#---Alphanetworks: hendry


##
# set various debug modes
##

if [ "${DEBUGMODE}" = "" ]; then
    DEBUGMODE=0x100
fi

if [ "${HALDEBUG}" = "" ]; then
    HALDEBUG=0x0
fi

if [ "${ATHDEBUG}" = "" ]; then
    ATHDEBUG=0x0
fi

#+++ Alphanetworks: Hendry.
#iwpriv wifi$IFNUM HALDbg $HALDEBUG
#--- Alphanetworks: Hendry.

#iwpriv wifi$IFNUM ATHDebug $ATHDEBUG
iwpriv ${APNAME} dbgLVL $DEBUGMODE

##
## Operating Mode passed in through call.  Determine the frequeny, or if a
## scan is required
##

if [ $PRI_CH = 11na -o $PRI_CH = 11ng ]; then
    FREQ="freq 0"
else
    FREQ="freq $PRI_CH"
fi

if [ "${AP_CHANBW}" != "" ]; then
    #
    # Channel bandwidth was specified
    #

    iwpriv ${APNAME} chanbw ${AP_CHANBW}
fi
#####################################################################
## Check for RF command. If so, set the RF parameters, else do the
## simple cofiguration.
##

if [ "${RF}" = "RF" ]; then

    #
    # 11n configuration section
    # increase queue length
    #

    ifconfig ${APNAME} txqueuelen $TXQUEUELEN
    ifconfig wifi$IFNUM txqueuelen $TXQUEUELEN

    # turn on halfgi
    iwpriv ${APNAME} shortgi $R_SHORTGI

	#+++ Alphanetworks: new driver doesn't have this.
    #iwpriv ${APNAME} noedgech $NO_EDGE_CH
	#--- Alphanetworks: new driver doesn't have this.

    iwpriv ${APNAME} mode $CH_MODE

    #
    # Check to see if we are in one of the 11NG bands that require
    # ANI processing
    #

    BAND=`echo $CH_MODE | grep 11NG`

    if [ "${BAND}" != "" ]; then
        iwpriv wifi$IFNUM ForBiasAuto 1
    fi

    IS11G=`echo $CH_MODE | grep 11G`
    IS11NG=`echo $CH_MODE | grep 11NG`
    IS11AC=`echo $CH_MODE | grep 11AC`

    if [ "${IS11G}" != "" -o "${IS11NG}" != "" ]; then
        iwpriv ${APNAME} vap_doth 0
    fi

####################
####### TEMP WORKAROUND
####################

    #PLUS=`echo $CH_MODE | grep PLUS`
    #MINUS=`echo $CH_MODE | grep MINUS`
    #
    #if [ "${PLUS}" != "" ]; then
    #    iwpriv ${APNAME} extoffset 1
    #fi
    #if [ "${MINUS}" != "" ]; then
    #    iwpriv ${APNAME} extoffset -1
    #fi

#######################

    if [ "x${IS11AC}" = "x" ]; then
        # Set Aggregation State
        iwpriv wifi$IFNUM AMPDU $R_AMPDUENABLE
        # set number of sub-frames in an ampdu
        iwpriv wifi$IFNUM AMPDUFrames $R_AMPDUFRAMES
        # set ampdu limit
        iwpriv wifi$IFNUM AMPDULim $R_AMPDULIMIT
        # 'g'-only mode (no 'b' stations)
        iwpriv ${APNAME} pureg $PUREG
        # 'n'-only mode (no legacy b/g/a stations)
        iwpriv ${APNAME} puren $PUREN
    else
        # 11AC parameters
        iwpriv ${APNAME} amsdu $AMSDU
        iwpriv ${APNAME} ampdu $AMPDU
        chan_width=`echo $CH_MODE | cut -b8-9`
        if [ "$chan_width" == "80" ]; then
            CH_WIDTH=3
        elif [ "$chan_width" == "40" ]; then
            CH_WIDTH=2
        else
            CH_WIDTH=1
        fi
        # iwpriv ${APNAME} chwidth ${CH_WIDTH}
        # iwpriv ${APNAME} nss $NSS
        # 11n station can't communicate with 11ac ap
        # once vhtmcs parameter is set, so we don't set
        # it at this time
        # iwpriv ${APNAME} vhtmcs $VHTMCS
        iwpriv ${APNAME} ldpc $LDPC
    fi
    #
    # set SSID and frequency
    #

    if [ "_${ESSID}" != "_any" ]; then
    	iwconfig ${APNAME} essid "${ESSID}" ${APMODE} ${FREQ}
    else
        iwconfig ${APNAME} ${APMODE} ${FREQ}
    fi

    #
    # IBSS setup channel
    # IBSS aggregation
    #
    if [ "${MODE}" = "adhoc" ]; then
        iwconfig ${APNAME} channel ${AP_PRIMARY_CH}
        iwpriv ${APNAME} ampdu $AMPDUENABLE
    fi

    #
    # If rate control is not auto, set the manual settings
    #

    if [ "${RATECTL}" != "auto" ]; then
        iwpriv ${APNAME} set11NRates $MANRATE
        iwpriv ${APNAME} set11NRetries $MANRETRIES
    fi

    #
    # Set the chain masks
    #

    if [ "${R_TXCHAIN}" != "" -a "${R_TXCHAIN}" != "0" ]; then
        iwpriv wifi$IFNUM txchainmask $R_TXCHAIN
	fi

    if [ "${R_RXCHAIN}" != ""  -a "${R_RXCHAIN}" != "0" ]; then
        iwpriv wifi$IFNUM rxchainmask $R_RXCHAIN
    fi

    #
    # An extra IE is provided for Intel interop
    #

	#+++ Alphanetworks: Hendry, whats this ? The proc isn't created
    #echo 1 > /proc/sys/dev/ath/htdupieenable
    #--- Alphanetworks: Hendry

    #
    # This is where extra commands are executed.
    #

    if [ "${AP_EXTRA}" != "" ]; then
        echo $AP_EXTRA | grep ';'
        #There is at least one command that ends with ';'
        if [ "$?" -eq "0" ]; then
            _more_cmds=1
            while [ ${_more_cmds} -ne 0 ];
            do
                _cmd=`echo $AP_EXTRA | cut -f $_more_cmds -d ';'`
                if [ "${_cmd}" != "" ];
                then
                    $_cmd
                    _more_cmds=`expr $_more_cmds + 1`
                else
                    _more_cmds=0
                fi
                _cmd=""
            done
        else
            #probably user setting did not have a ';', cut command fails if
            #not set
            ${AP_EXTRA}
        fi
    fi

else
    ####
    # set SSID only
    ###

    iwpriv ${APNAME} mode ${CH_MODE}
    iwconfig ${APNAME} essid "${ESSID}" ${APMODE} ${FREQ}

fi

##
## Check for multiple VAPs.  If the VAP name is ath2 we assume we want the
## beacon interval to be 400 ms
##

if [ "${BEACONINT}" != "" ]; then
    #
    # Beacon interval was specified
    #

    iwpriv ${APNAME} bintval ${BEACONINT}
fi

#VOW related configurations
#echo "Setting VoW function .. " > /dev/console
#if [ "${IFNUM}" = "0" ]; then
#    if [ "${VOW_ENABLE}" = "1" ]; then
#    #apply all commands if video enabled
#    #All video options are enabled by default and no dynamic configuration
#        ifconfig ${APNAME} allmulti
#        iwpriv ${APNAME} mcastenhance 2
#        iwpriv $(APNAME) acparams 1 0 1 0
#        iwpriv wifi0 setKeySrchAlways 1
#        iwpriv wifi0 setPhyRestartWar 1
#    else
#        iwpriv wifi0 setVowExt 0
#        ifconfig ${APNAME} -allmulti
#        iwpriv wifi0 setKeySrchAlways 0
#        iwpriv ${APNAME} mcastenhance 0
#        iwpriv $(APNAME) acparams 1 0 0 0
#        iwpriv wifi0 set_vsp_enable 0
#        iwpriv wifi0 setPhyRestartWar 0
#    fi
#
#    if [ "${VOW_DEBUG}" = "1" ]; then
#        iwpriv wifi0 setVowExtStats 1
#    else
#        iwpriv wifi0 setVowExtStats 0
#    fi
#fi
#
#if [ "${IFNUM}" = "1" ]; then
#    if [ "${VOW_ENABLE_2}" = "1" ]; then
#    #apply all commands if video enabled
#    #All video options are enabled by default and no dynamic configuration
#        ifconfig ${APNAME} allmulti
#        iwpriv ${APNAME} mcastenhance 2
#        iwpriv $(APNAME) acparams 1 0 1 0
#        iwpriv wifi1 setKeySrchAlways 1
#        iwpriv wifi1 setPhyRestartWar 1
#    else
#        iwpriv wifi1 setVowExt 0
#        ifconfig ${APNAME} -allmulti
#        iwpriv wifi1 setKeySrchAlways 0
#        iwpriv ${APNAME} mcastenhance 0
#        iwpriv $(APNAME) acparams 1 0 0 0
#        iwpriv wifi1 set_vsp_enable 0
#        iwpriv wifi1 setPhyRestartWar 0
#    fi
#
#    if [ "${VOW_DEBUG_2}" = "1" ]; then
#        iwpriv wifi1 setVowExtStats 1
#    else
#        iwpriv wifi1 setVowExtStats 0
#    fi
#fi

if [ "${AP_HIDESSID}" = "1" ]; then
     iwpriv ${APNAME} hide_ssid 1
fi


#Alphanetworks: hendry. We add settings for wmm.
#if [ "${AP_WMM}" = "1" ]; then
#	iwpriv ${APNAME} wmm 1
#else
#	iwpriv ${APNAME} wmm 0
#fi

#Alphanetworks: hendry. We add settings based on recommendation from David (Atheros FAE)
#iwpriv wifi$IFNUM burst 1

##
## Script Complete
##

echo Created ${APNAME} mode ${MODE} for "${ESSID}"
