/*
 We should refresh the WD style button in these places.
  1.The end of COMM_GetCFG function.
  2.The end of NewCheckRadio.check function.
  3.The end of NewSelect.select function. 
  4.The end of PAGE.ShowCurrentStage() in every WD wizard.
*/
/*
 We should initialize the WD style button when the buttons are generated by Javascript instantaneously.
*/
var button_hover = new Array();
var button_normal = new Array();
button_hover["button_blue"]="url(/pic/bg_button_blue_hover.png)";
button_hover["button_blueX05"]="url(/pic/bg_button_blueX05_hover.png)";
button_hover["button_blueX1"]="url(/pic/bg_button_blueX1_hover.png)";
button_hover["button_blueX1p5"]="url(/pic/bg_button_blueX1p5_hover.png)";
button_hover["button_blueX2"]="url(/pic/bg_button_blueX2_hover.png)";
button_hover["button_blueX3"]="url(/pic/bg_button_blueX3_hover.png)";
button_hover["button_blueX4"]="url(/pic/bg_button_blueX4_hover.png)";
button_hover["button_blueX5"]="url(/pic/bg_button_blueX5_hover.png)";
button_hover["button_black"]="url(/pic/bg_button_black_hover.png)";
button_hover["button_blackX05"]="url(/pic/bg_button_blackX05_hover.png)";
button_hover["button_blackX1"]="url(/pic/bg_button_blackX1_hover.png)";
button_hover["button_blackX2"]="url(/pic/bg_button_blackX2_hover.png)";
button_hover["button_blackX3"]="url(/pic/bg_button_blackX3_hover.png)";
button_hover["button_blackX4"]="url(/pic/bg_button_blackX4_hover.png)";
button_hover["button_blackX5"]="url(/pic/bg_button_blackX5_hover.png)";
button_normal["button_blue"]="url(/pic/bg_button_blue.png)";
button_normal["button_blueX05"]="url(/pic/bg_button_blueX05.png)";
button_normal["button_blueX1"]="url(/pic/bg_button_blueX1.png)";
button_normal["button_blueX1p5"]="url(/pic/bg_button_blueX1p5.png)";
button_normal["button_blueX2"]="url(/pic/bg_button_blueX2.png)";
button_normal["button_blueX3"]="url(/pic/bg_button_blueX3.png)";
button_normal["button_blueX4"]="url(/pic/bg_button_blueX4.png)";
button_normal["button_blueX5"]="url(/pic/bg_button_blueX5.png)";
button_normal["button_black"]="url(/pic/bg_button_black.png)";
button_normal["button_blackX05"]="url(/pic/bg_button_blackX05.png)";
button_normal["button_blackX1"]="url(/pic/bg_button_blackX1.png)";
button_normal["button_blackX2"]="url(/pic/bg_button_blackX2.png)";
button_normal["button_blackX3"]="url(/pic/bg_button_blackX3.png)";
button_normal["button_blackX4"]="url(/pic/bg_button_blackX4.png)";
button_normal["button_blackX5"]="url(/pic/bg_button_blackX5.png)";


function button_disabled(obj,stat)
{
	if(stat==true)
	{	
		obj.style.backgroundImage=button_hover[obj.className];
	}
	else
	{
		obj.style.backgroundImage=button_normal[obj.className];		
	}
	
}
function New_button(){}
New_button.prototype = 
{
	init: function() 
	{
		var inputs = document.getElementsByTagName("input");
		for(var a = 0; a < inputs.length; a++) 
		{
			if(inputs[a].type=="button" && (inputs[a].className=="button_blue" ||inputs[a].className=="button_blueX2" 
			||inputs[a].className=="button_blueX1p5"||inputs[a].className=="button_blueX3" ||inputs[a].className=="button_blueX4"
			||inputs[a].className=="button_blueX5" || inputs[a].className=="button_black"
			|| inputs[a].className=="button_blueX05" || inputs[a].className=="button_blackX05"
			|| inputs[a].className=="button_blackX2"|| inputs[a].className=="button_blackX3"
			|| inputs[a].className=="button_blackX4"|| inputs[a].className=="button_blackX5")) 
			{
				inputs[a].onmouseover = NewButton.mouseover;
				inputs[a].onmouseout = NewButton.mouseout;
			}
		}
	},
	mouseover: function() 
	{
		this.style.backgroundImage=button_hover[this.className];
	},
	mouseout: function()
	{
		this.style.backgroundImage=button_normal[this.className];
	},
	refresh: function() 
	{
		var inputs = document.getElementsByTagName("input");
		for(var a = 0; a < inputs.length; a++) 
		{
			var input_className_substr11 = inputs[a].className.substring(0,11);
			if(inputs[a].type=="button" && 
			(input_className_substr11=="button_blue" || input_className_substr11=="button_blac")) 
			{
				if(inputs[a].disabled) inputs[a].style.color = "gray";
				else inputs[a].style.color = "white";
			}
		}
	}				
}
