/*
 We should refresh the WD style check box and radio button in these places.
  1.The end of COMM_GetCFG function.
  2.The end of COMM_SetRadioValue function.
  3.The end of NewSelect.select function. 
  4.The end of PAGE.ShowCurrentStage() in every WD wizard.
*/
/*
 We should initialize the WD style select when the checkbox and radio items are generated by Javascript instantaneously.
  Ex: parent_ctrl.php
*/
function New_checkbox_radio(){}
New_checkbox_radio.prototype = 
{
	init: function() 
	{
		var inputs = document.getElementsByTagName("input");
		var span = Array();
		for(var a = 0; a < inputs.length; a++) 
		{
			if((inputs[a].type == "checkbox" || inputs[a].type == "radio") && (inputs[a].className == "styled" || inputs[a].className == "styled2")) 
			{
				if(!NewCheckRadio.overlap(inputs[a]))
				{
					span[a] = document.createElement("span");
					
					if(inputs[a].type == "checkbox" && inputs[a].className == "styled")
					{
						span[a].className = inputs[a].type;
						if(inputs[a].checked == false && inputs[a].disabled == false) span[a].style.backgroundImage = "url(/pic/checkbox_off.png)";
						else if(inputs[a].checked == false && inputs[a].disabled == true) span[a].style.backgroundImage = "url(/pic/checkbox_off_disable.png)";
						else if(inputs[a].checked == true && inputs[a].disabled == false) span[a].style.backgroundImage = "url(/pic/checkbox.png)";
						else if(inputs[a].checked == true && inputs[a].disabled == true) span[a].style.backgroundImage = "url(/pic/checkbox_disable.png)";				
					}
					else if(inputs[a].type == "checkbox" && inputs[a].className == "styled2")
					{
						span[a].className = "checkbox2";
						if(inputs[a].checked == false && inputs[a].disabled == false) span[a].style.backgroundImage = "url(/pic/checkbox2_off.png)";
						else if(inputs[a].checked == false && inputs[a].disabled == true) span[a].style.backgroundImage = "url(/pic/checkbox2_off_disable.png)";
						else if(inputs[a].checked == true && inputs[a].disabled == false) span[a].style.backgroundImage = "url(/pic/checkbox2.png)";
						else if(inputs[a].checked == true && inputs[a].disabled == true) span[a].style.backgroundImage = "url(/pic/checkbox2_disable.png)";				
					}				
					else if(inputs[a].type == "radio")
					{
						span[a].className = inputs[a].type;
						if(inputs[a].checked == false && inputs[a].disabled == false) span[a].style.backgroundImage = "url(/pic/radio_off.png)";
						else if(inputs[a].checked == false && inputs[a].disabled == true) span[a].style.backgroundImage = "url(/pic/radio_off_disable.png)";
						else if(inputs[a].checked == true && inputs[a].disabled == false) span[a].style.backgroundImage = "url(/pic/radio_on.png)";
						else if(inputs[a].checked == true && inputs[a].disabled == true) span[a].style.backgroundImage = "url(/pic/radio_on_disable.png)"; 						
					}		
					
					inputs[a].parentNode.insertBefore(span[a], inputs[a]);
					span[a].onclick = NewCheckRadio.check;
				}
			}
		}
	},	
	overlap: function(inputs_a)
	{
		var element = inputs_a.previousSibling;
		if(element==null) return false;
		else if(element.nodeType==1)
		{
			if(element.tagName!="SPAN") return false;
			else if(element.className==null) return false;
			else if(element.className=="checkbox" || element.className=="checkbox2" || element.className=="radio") return true;
		}
		return false;	
	},
	check: function() 
	{
		element = this.nextSibling;
		
		if(element.disabled != true)
		{
			if(element.type == "checkbox")
			{
				if(element.checked == true) element.checked = false;
				else element.checked = true;
			}
			else if(element.type == "radio")
			{
				if(element.checked == false) element.checked = true;
			}			
			if(element.onclick != null) element.onclick();
			BODY.NewWDStyle_refresh();
		}
	},
	refresh: function()
	{
		inputs = document.getElementsByTagName("input");
		
		for(var b = 0; b < inputs.length; b++) 
		{
			if(inputs[b].type == "checkbox" && inputs[b].className == "styled") 
			{
				if(inputs[b].checked == false && inputs[b].disabled == false) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox_off.png)";
				else if(inputs[b].checked == false && inputs[b].disabled == true) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox_off_disable.png)";
				else if(inputs[b].checked == true && inputs[b].disabled == false) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox.png)";
				else if(inputs[b].checked == true && inputs[b].disabled == true) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox_disable.png)";
			}
			else if(inputs[b].type == "checkbox" && inputs[b].className == "styled2") 
			{
				if(inputs[b].checked == false && inputs[b].disabled == false) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox2_off.png)";
				else if(inputs[b].checked == false && inputs[b].disabled == true) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox2_off_disable.png)";
				else if(inputs[b].checked == true && inputs[b].disabled == false) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox2.png)";
				else if(inputs[b].checked == true && inputs[b].disabled == true) inputs[b].previousSibling.style.backgroundImage = "url(/pic/checkbox2_disable.png)";
			}			
			else if(inputs[b].type == "radio" && inputs[b].className == "styled") 
			{
				if(inputs[b].checked == false && inputs[b].disabled == false) inputs[b].previousSibling.style.backgroundImage = "url(/pic/radio_off.png)";
				else if(inputs[b].checked == false && inputs[b].disabled == true) inputs[b].previousSibling.style.backgroundImage = "url(/pic/radio_off_disable.png)";
				else if(inputs[b].checked == true && inputs[b].disabled == false) inputs[b].previousSibling.style.backgroundImage = "url(/pic/radio_on.png)";
				else if(inputs[b].checked == true && inputs[b].disabled == true) inputs[b].previousSibling.style.backgroundImage = "url(/pic/radio_on_disable.png)";			
			}			
		}
	}		
}