/*
 We should refresh the WD style select in these places.
  1.The end of COMM_GetCFG function.
  2.The end of COMM_SetSelectValue function.
  3.The end of NewCheckRadio.check function.
  4.The end of PAGE.ShowCurrentStage() in every WD wizard.
*/
/*
 We should initialize the WD style select when the select items are generated by Javascript instantaneously.
  Ex: adv_qos.php
*/
function New_select(){}
New_select.prototype = 
{
	init: function() 
	{
		var selects = document.getElementsByTagName("select"), span = Array(), textnode, option, active;
		for(var a = 0; a < selects.length; a++) 
		{
			var select_className_substr6 = selects[a].className.substring(0,6);
			if(select_className_substr6=="styled")
			{
				if(!NewSelect.overlap(selects[a]))
				{
					option = selects[a].getElementsByTagName("option");
					active = option[0].childNodes[0].nodeValue;
					textnode = document.createTextNode(active);
					for(var b = 0; b < option.length; b++) 
					{
						if(option[b].selected) textnode = document.createTextNode(option[b].childNodes[0].nodeValue);
					}
					span[a] = document.createElement("span");
					span[a].className = "select_"+selects[a].className;
					span[a].appendChild(textnode);
					selects[a].parentNode.insertBefore(span[a], selects[a]);
								
					try{
						selects[a].addEventListener('change',NewSelect.select,false);//For FF, Chrome, Safari...
					}
					catch(e){
						try{
							selects[a].attachEvent('onchange',NewSelect.select);//For IE
						}catch(e){};
					}
				}	
			}
		}
	},
	overlap: function(select)
	{
		var element = select.previousSibling;
		if(element==null) return false;
		else if(element.nodeType==1)
		{
			if(element.tagName!="SPAN") return false;
			else if(element.className==null) return false;
			else if(element.className.substring(0,13)=="select_styled") return true;
		}		 	
		else if(element.previousSibling==null) return false;
		else if(element.previousSibling.nodeType==1)
		{
			if(element.previousSibling.tagName!="SPAN") return false;
			else if(element.previousSibling.className==null) return false;
			else if(element.previousSibling.className.substring(0,13)=="select_styled") return true;
		}
		return false;	
	},
	select: function() 
	{
		BODY.NewWDStyle_refresh();
	},
	refresh: function() 
	{
		var selects = document.getElementsByTagName("select");
		for(var a = 0; a < selects.length; a++) 
		{
			var select_className_substr6 = selects[a].className.substring(0,6);
			if(select_className_substr6=="styled")
			{
				var option = selects[a].getElementsByTagName("option");
				for(var d = 0; d < option.length; d++) 
				{
					if(option[d].selected) 
					{
						selects[a].previousSibling.childNodes[0].nodeValue = option[d].childNodes[0].nodeValue;
					}
				}
				if(selects[a].disabled) selects[a].previousSibling.style.color = "gray";
				else selects[a].previousSibling.style.color = "white";
			}	
		}			
	}			
}