/*
 We should refresh the WD style button in these places.
  1.The end of COMM_GetCFG function.
  2.The end of NewCheckRadio.check function.
  3.The end of NewSelect.select function. 
  4.The end of PAGE.ShowCurrentStage() in every WD wizard.
*/
/*
 We should initialize the WD style button when the buttons are generated by Javascript instantaneously.
*/
var arrow_hover = new Array();
var arrow_normal = new Array();
arrow_hover["RightArrow"]="url(/pic/button_right_over.png)";
arrow_hover["LeftArrow"]="url(/pic/button_left_over.png)";
arrow_hover["UpArrow"]="url(/pic/button_up_over.png)";
arrow_hover["DownArrow"]="url(/pic/button_down_over.png)";
arrow_normal["RightArrow"]="url(/pic/button_right.png)";
arrow_normal["LeftArrow"]="url(/pic/button_left.png)";
arrow_normal["UpArrow"]="url(/pic/button_up.png)";
arrow_normal["DownArrow"]="url(/pic/button_down.png)";

function New_arrow(){}
New_arrow.prototype = 
{
	init: function() 
	{
		var img = document.getElementsByTagName("img");
		for(var a = 0; a < img.length; a++) 
		{
			if(
			img[a].className=="RightArrow" || img[a].className=="LeftArrow" ||
			img[a].className=="UpArrow" || img[a].className=="DownArrow"
			)
			{
				img[a].onmouseover = NewArrow.mouseover;
				img[a].onmouseout = NewArrow.mouseout;
			}
		}
	},
	mouseup: function()
	{
		/* future use */
	},
	mousedown: function()
	{
		/* future use */
	},
	mouseover: function() 
	{
		this.style.backgroundImage=arrow_hover[this.className];
	},
	mouseout: function()
	{
		this.style.backgroundImage=arrow_normal[this.className];
	},
	refresh: function() 
	{
		/* No need to do refresh because image doesn't have disable attribute. */
	}
}