#!/bin/sh
#
# PROVIDE: mtdaapd mt-daapd
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# mt-daapd daemon.
#
# Created by Patrick Lemmens for NetBSD and FreeBSD.

. /etc/rc.subr

name="mtdaapd"
realname="mt-daapd"
rcvar=$name
command="/home/jeremy_lin/project/GPL/0514_pro/elbox_WRGND15/rootfs/bin/${realname}"
pidfile="/var/run/${realname}.pid"
sig_stop="SIGINT"
 
load_rc_config $name
run_rc_command "$1"